# Generated by Django 3.2.9 on 2021-11-09 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AoEMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCategoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchEconomyStats',
            fields=[
                ('playercategorystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aoe4.playercategorystats')),
                ('score', models.IntegerField()),
                ('food', models.IntegerField()),
                ('wood', models.IntegerField()),
                ('stone', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('max_food_per_min', models.IntegerField()),
                ('max_wood_per_min', models.IntegerField()),
            ],
            bases=('aoe4.playercategorystats',),
        ),
        migrations.CreateModel(
            name='PlayerMatchMilitaryStats',
            fields=[
                ('playercategorystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aoe4.playercategorystats')),
                ('score', models.IntegerField()),
                ('units_killed', models.IntegerField()),
                ('units_lost', models.IntegerField()),
                ('buildings_razed', models.IntegerField()),
                ('buildings_lost', models.IntegerField()),
                ('largest_army', models.IntegerField()),
            ],
            bases=('aoe4.playercategorystats',),
        ),
        migrations.CreateModel(
            name='PlayerMatchSocietyStats',
            fields=[
                ('playercategorystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aoe4.playercategorystats')),
                ('score', models.IntegerField()),
                ('relics_captured', models.IntegerField()),
                ('villager_high', models.IntegerField()),
                ('avg_villager_idle', models.TimeField()),
                ('avg_unit_lifespan', models.TimeField()),
            ],
            bases=('aoe4.playercategorystats',),
        ),
        migrations.CreateModel(
            name='PlayerMatchTechnologyStats',
            fields=[
                ('playercategorystats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aoe4.playercategorystats')),
                ('score', models.IntegerField()),
                ('time_to_age_2', models.TimeField()),
                ('time_to_age_3', models.TimeField()),
                ('time_to_age_4', models.TimeField()),
                ('map_explored', models.IntegerField()),
                ('research_count', models.IntegerField()),
            ],
            bases=('aoe4.playercategorystats',),
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoe4.aoematchstats')),
                ('match_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoe4.matchplayer')),
            ],
        ),
        migrations.AddField(
            model_name='playercategorystats',
            name='match_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoe4.playermatchstats'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aoe4.player'),
        ),
    ]
